### ISSUE TITLE
Program is running, doesn't work?

### ISSUE THREAD

**Issue by bresslau** [Eun/MoveToDesktop#30] opened 2016-09-15 12:14 UTC
I downloaded MoveToDesktop-1.4.zip, extracted the file to a local folder, ran it as admin. Nothing happened. Killed the 2 processes and ran again, nothing. Downloaded the INI file, saved it to %AppData% and ran the executable again. Nothing. The menu item does not appear, the shortcut keys (win+alt+arrow) don't work. I am on Windows 10 Pro, updated today.

Am I missing something?

**Comment by M3Rocket** [comment] 2016-09-15 18:01
Try version 1.3 if your Windows 10 version is 1511 or lower. I've found that version 1.4 only works with 1607 (anniversary edition/update).

To find your build number, just click on Windows Start, type "About," select "About your PC." There should be a "Version" shown.

**Comment by Eun** [comment] 2016-09-15 19:23
That is true, 1.4 only supports the Anniversary Update.

**Comment by bresslau** [comment] 2016-09-19 14:59
I installed 1.3, it works, thanks! Very handy!

**Comment by M3Rocket** [comment] 2016-10-03 18:20
@bresslau You may want to close this issue since the problem is solved.

**Closed as completed** 2016-10-03 18:53 UTC
